name: "ark"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0/20 23 * * *'

jobs:
  ark:
    runs-on: ubuntu-latest
    steps:
      - run: echo -n ""
      - run: curl 'https://ak.hypergryph.com/activity/preparation/activity/share' -H 'Content-Type:'' application/json;charset=utf-8' -H "$YJ_COOKIE" --data-raw '{"method":1}' -o output0.txt
      - run: curl 'https://ak.hypergryph.com/activity/preparation/activity/roll' -H "$YJ_COOKIE" --data-raw '{}' -o output1.txt
      - run: curl 'https://ak.hypergryph.com/activity/preparation/activity/userInfo' -H "$YJ_COOKIE" -o output2.txt
      - run: curl 'https://ak.hypergryph.com/activity/preparation/activity/meta' -H "$YJ_COOKIE" -o output3.txt
      - run: echo `cat output0.txt output1.txt output2.txt output3.txt`
      - id: yj_outout
        run: echo "::set-output name=yj_output::明日方舟二周年签到 `cat output0.txt output1.txt output2.txt output3.txt`"
      
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.yj_outout.outputs.yj_output }}
    env:
      YJ_COOKIE: ${{ secrets.YJ_COOKIE }}
