name: "greenpoint"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0/20 4 * * *'

jobs:
  greenpoint:
    runs-on: ubuntu-latest
    steps:
      - run: echo -n 'startTime='`date --rfc-3339=date`'%2013%3A00%3A00&endTime='`date --rfc-3339=date`'%2014%3A00%3A00&'$GP_1 | tee data.txt
      - run: curl 'https://wzhz.wenzhou.gov.cn/userPatrolApp/addPatrolByGreen?token='$GP_TOKEN --data-raw `cat data.txt` -o output1.txt
      - run: curl 'https://wzhz.wenzhou.gov.cn/pointApp/getUserPointInfo?token='$GP_TOKEN -o output2.txt
      - id: gp_outout
        run: echo "::set-output name=gp_output::`cat output1.txt output2.txt`"
      
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ toJSON(steps.gp_outout.outputs.gp_output) }}
    env:
      GP_TOKEN: ${{ secrets.GP_TOKEN }}
      GP_1: ${{ secrets.GP_1 }}
