name: "greenpoint"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0/20 4 * * *'

jobs:
  greenpoint:
    runs-on: ubuntu-latest
    steps:
      - run: curl 'https://wzhz.wenzhou.gov.cn/pointApp/getUserPointInfo?token='$GP_TOKEN -O output.txt
      - id: gp_outout
        run: echo "::set-output name=gp_output::`cat output.txt`"
      
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.gp_outout.outputs.gp_outout }}
    env:
      GP_TOKEN: ${{ secrets.GP_TOKEN }}
