name: jd

on:
  schedule:
  - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  JD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
    - run: npm install request
    - run: curl "https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js" -O
    - run: sed -iE "s| Key = ''| Key = '$JD_COOKIE'|" JD_DailyBonus.js
    - id: output
      run: node JD_DailyBonus.js
      
    - name: send custom message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ toJSON(steps) }}
    env:
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
