name: jd

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  JD:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v2
    - run: npm install request
    - run: curl "https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js" -O
    - run: sed -iE "s| Key = ''| Key = '$JD_COOKIE'|" JD_DailyBonus.js
    - run: node JD_DailyBonus.js
    env:
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
